# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bilt < Formula
  desc "Build and install your Bilt app on your iPhone"
  homepage "https://bilt.me"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buildingapplications/bilt-cli/releases/download/v0.1.0/bilt-cli_darwin_amd64.tar.gz"
      sha256 "f7d59032601ea76783450af21ee3123d2912992a49d3cd0211248ef157a6e0d8"

      define_method(:install) do
        bin.install "bilt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buildingapplications/bilt-cli/releases/download/v0.1.0/bilt-cli_darwin_arm64.tar.gz"
      sha256 "1039059828bf3ce8701600afd387ae51c23ccbe2359ea4f4e62aec3fa7285a42"

      define_method(:install) do
        bin.install "bilt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildingapplications/bilt-cli/releases/download/v0.1.0/bilt-cli_linux_amd64.tar.gz"
      sha256 "d5ff33f989b43958bb468e308cb2a5ea6559536b883a9ae1ab9c9b5063c91ac8"
      define_method(:install) do
        bin.install "bilt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildingapplications/bilt-cli/releases/download/v0.1.0/bilt-cli_linux_arm64.tar.gz"
      sha256 "96f1464a578f02a63043bbb2ce9ce8428a5de94f356bd5be2e96164c5b719edc"
      define_method(:install) do
        bin.install "bilt"
      end
    end
  end

  test do
    system "#{bin}/bilt", "--help"
  end
end
