# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bilt < Formula
  desc "Build and install your Bilt app on your iPhone"
  homepage "https://bilt.me"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/buildingapplications/bilt-cli/releases/download/v0.2.0/bilt-cli_darwin_amd64.tar.gz"
      sha256 "ad14b206501a14ecd8e8d65e4b4675bb7d5b25b00b719806c58a91be29e9f280"

      define_method(:install) do
        bin.install "bilt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/buildingapplications/bilt-cli/releases/download/v0.2.0/bilt-cli_darwin_arm64.tar.gz"
      sha256 "f6937204e650c45685b2178a767a4dbecd553e8b1a6c03ef8b1db645b13b2bc3"

      define_method(:install) do
        bin.install "bilt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildingapplications/bilt-cli/releases/download/v0.2.0/bilt-cli_linux_amd64.tar.gz"
      sha256 "ef3023ac3f6f07029e1118918ff7a5275b01fe53bee142a051e89b24e32e3b62"
      define_method(:install) do
        bin.install "bilt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/buildingapplications/bilt-cli/releases/download/v0.2.0/bilt-cli_linux_arm64.tar.gz"
      sha256 "6b6d80964269dc62870d0d7ee70d135135d19a28881084fcf7ed2cd59e1ef980"
      define_method(:install) do
        bin.install "bilt"
      end
    end
  end

  test do
    system "#{bin}/bilt", "--help"
  end
end
